name: Debug Build

on:
  push:
    branches-ignore: [main, gh-pages]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "NewHorizons/Schemas/*.json"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  Build:
    uses: "./.github/workflows/build.yaml"
    with:
      build_type: Debug
  Update_Schemas:
    name: "Update Schemas"
    needs: Build
    if: ${{ needs.Build.outputs.schemas_changed == 'true' }}
    uses: "./.github/workflows/update_schemas.yml"
    with:
      artifact_name: NewHorizons-Schemas-Debug
    secrets: inherit
